const Refs = {
     headerListRef: document.querySelectorAll('.header__list-item'),
     headerAfterRef : document.querySelectorAll('.header__list-container'),
     list : document.querySelector('.main__list'),
     links : document.querySelectorAll('.main__list-item'),
     innerContainer : document.querySelector('.main__inner-container'),
     innerItems : document.querySelectorAll('.main__inner-item'),
     innerList : document.querySelector('.main__inner-list'),
     innerImgLink : document.querySelectorAll('.main__inner-img-link'),
     innerImg : document.querySelectorAll('.main__inner-img'),
     innerTitle : document.querySelector('.main__inner-title'),
     innerBtn : document.querySelector('.main__inner-btn'),
     overlayRef: document.querySelector('.Overlay'),
     overlayRef1 : document.querySelector('.Overlay1'),
     modalRef: document.querySelector('.Modal'),
     modalRef1: document.querySelector('.Modal1'),
     modalImgRef : document.querySelector('.modal__img'),
     btnNext : document.querySelector('.modal__btn--next'),
     btnPrev: document.querySelector('.modal__btn--prev'),
     svipeRef: document.querySelector('.slider'),
}
export default Refs;